#pragma once

enum class CardType { UNIT, HERO,SIEGE_MACHINE, ABILITY, WEATHER };
enum class CombatZone { CLOSE, RANGED, SIEGE, ANY };
enum class Faction { NORTH, SCOIATAEL, NILFGARD, MONSTERS, NEUTRAL };

enum class WeatherType {
    BITING_FROST, IMPENETRABLE_FOG, TORRENTIAL_RAIN,
    CLEAR_WEATHER, NONE
};

enum class DeployEffect {
    NONE, DAMAGE_RANDOM_ENEMY, BOOST_ADJACENT, DRAW_CARD,
    DESTROY_WEAKEST, CLEAR_WEATHER, SPY, MEDIC, MORALE_BOOST
};

enum class HeroAbility {
    COMMANDERS_HORN, SCORCH, DECOY, ALCHEMY, REVENGE
};

enum class AbilityEffect {
    DAMAGE_ROW, CLEAR_SKIES, FOGLET_SPAWN, 
    COMMANDO_TRAINING, VENOM_EXTRACT
};
